CREATE OR REPLACE WAREHOUSE COMPUTE_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE AIRLINE_DWH;

USE DATABASE AIRLINE_DWH;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA ANALYTICS;
CREATE OR REPLACE SCHEMA AUDIT;

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE ROLE AIRFLOW_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON DATABASE AIRLINE_DWH TO ROLE AIRFLOW_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE AIRLINE_DWH TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AIRLINE_DWH TO ROLE AIRFLOW_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA AIRLINE_DWH.RAW TO ROLE AIRFLOW_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AIRLINE_DWH.RAW TO ROLE AIRFLOW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA AIRLINE_DWH.STAGING TO ROLE AIRFLOW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA AIRLINE_DWH.STAGING TO ROLE AIRFLOW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA AIRLINE_DWH.ANALYTICS TO ROLE AIRFLOW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA AIRLINE_DWH.ANALYTICS TO ROLE AIRFLOW_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA AIRLINE_DWH.AUDIT TO ROLE AIRFLOW_ROLE;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA AIRLINE_DWH.AUDIT TO ROLE AIRFLOW_ROLE;

GRANT SELECT ON ALL STREAMS IN SCHEMA AIRLINE_DWH.RAW TO ROLE AIRFLOW_ROLE;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA AIRLINE_DWH.RAW TO ROLE AIRFLOW_ROLE;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA AIRLINE_DWH.STAGING TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA AIRLINE_DWH.STAGING TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA AIRLINE_DWH.ANALYTICS TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA AIRLINE_DWH.ANALYTICS TO ROLE AIRFLOW_ROLE;

CREATE OR REPLACE USER AIRFLOW_USER
  PASSWORD = 'Wady123An_456789'
  LOGIN_NAME = 'Anlison_log'
  DEFAULT_ROLE = AIRFLOW_ROLE
  DEFAULT_WAREHOUSE = 'COMPUTE_WH'
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE AIRFLOW_ROLE TO USER AIRFLOW_USER;