USE WAREHOUSE COMPUTE_WH;
USE DATABASE AIRLINE_DWH;

CREATE OR REPLACE TABLE AIRLINE_DWH.RAW.RAW_AIRLINE_DATA (
    ROW_INDEX NUMBER,
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE NUMBER,
    NATIONALITY VARCHAR,
    AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR,
    DEPARTURE_DATE DATE,
    ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR
);

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGING.STG_FLIGHTS LIKE AIRLINE_DWH.RAW.RAW_AIRLINE_DATA;

CREATE OR REPLACE TABLE AIRLINE_DWH.ANALYTICS.DIM_PASSENGER (
    passenger_key NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    passenger_id VARCHAR,
    first_name VARCHAR,
    last_name VARCHAR,
    gender VARCHAR,
    age INTEGER,
    nationality VARCHAR,
    PRIMARY KEY (passenger_key)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.ANALYTICS.DIM_AIRPORT (
    airport_key NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    airport_name VARCHAR,
    airport_code VARCHAR,
    country_name VARCHAR,
    continent VARCHAR,
    PRIMARY KEY (airport_key)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.ANALYTICS.DIM_PILOT (
    pilot_key NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    pilot_name VARCHAR,
    PRIMARY KEY (pilot_key)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS (
    flight_key NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    passenger_key NUMBER,
    departure_airport_key NUMBER,
    arrival_airport_key NUMBER,
    pilot_key NUMBER,
    departure_date DATE,
    flight_status VARCHAR,
    ticket_type VARCHAR,
    FOREIGN KEY (passenger_key) REFERENCES AIRLINE_DWH.ANALYTICS.DIM_PASSENGER(passenger_key),
    FOREIGN KEY (departure_airport_key) REFERENCES AIRLINE_DWH.ANALYTICS.DIM_AIRPORT(airport_key),
    FOREIGN KEY (arrival_airport_key) REFERENCES AIRLINE_DWH.ANALYTICS.DIM_AIRPORT(airport_key),
    FOREIGN KEY (pilot_key) REFERENCES AIRLINE_DWH.ANALYTICS.DIM_PILOT(pilot_key)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.AUDIT.ETL_LOG (
    log_id INT AUTOINCREMENT,
    procedure_name VARCHAR,
    table_name VARCHAR,
    rows_inserted INT,
    rows_updated INT,
    log_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);