USE WAREHOUSE COMPUTE_WH;
USE DATABASE AIRLINE_DWH;
USE SCHEMA RAW;

CREATE OR REPLACE STREAM RAW_AIRLINE_DATA_STREAM ON TABLE RAW_AIRLINE_DATA;

CREATE OR REPLACE PROCEDURE AIRLINE_DWH.STAGING.sp_process_raw_to_staging()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  rows_inserted INT;
  error_message VARCHAR;
BEGIN
  BEGIN TRANSACTION;

  MERGE INTO AIRLINE_DWH.STAGING.STG_FLIGHTS stg
  USING (
    SELECT
        ROW_INDEX, PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE,
        NATIONALITY, AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME,
        AIRPORT_CONTINENT, CONTINENTS, DEPARTURE_DATE, ARRIVAL_AIRPORT,
        PILOT_NAME, FLIGHT_STATUS, TICKET_TYPE, PASSENGER_STATUS
    FROM AIRLINE_DWH.RAW.RAW_AIRLINE_DATA_STREAM
    WHERE METADATA$ACTION = 'INSERT'
  ) stream
  ON stg.Passenger_ID = stream.Passenger_ID AND stg.Departure_Date = stream.Departure_Date
  WHEN NOT MATCHED THEN
    INSERT (
        ROW_INDEX, PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE,
        NATIONALITY, AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME,
        AIRPORT_CONTINENT, CONTINENTS, DEPARTURE_DATE, ARRIVAL_AIRPORT,
        PILOT_NAME, FLIGHT_STATUS, TICKET_TYPE, PASSENGER_STATUS
    )
    VALUES (
        stream.ROW_INDEX, stream.PASSENGER_ID, stream.FIRST_NAME, stream.LAST_NAME, stream.GENDER, stream.AGE,
        stream.NATIONALITY, stream.AIRPORT_NAME, stream.AIRPORT_COUNTRY_CODE, stream.COUNTRY_NAME,
        stream.AIRPORT_CONTINENT, stream.CONTINENTS, stream.DEPARTURE_DATE, stream.ARRIVAL_AIRPORT,
        stream.PILOT_NAME, stream.FLIGHT_STATUS, stream.TICKET_TYPE, stream.PASSENGER_STATUS
    );

  rows_inserted := SQLROWCOUNT;

  INSERT INTO AIRLINE_DWH.AUDIT.ETL_LOG (procedure_name, table_name, rows_inserted)
  VALUES ('sp_process_raw_to_staging', 'STG_FLIGHTS', :rows_inserted);

  COMMIT;
  RETURN 'Processed ' || rows_inserted || ' rows.';

EXCEPTION
  WHEN OTHER THEN
    ROLLBACK;
    error_message := 'Error: ' || SQLERRM || ' (SQLSTATE: ' || SQLSTATE || ')';
    RETURN :error_message;
END;
$$;


CREATE OR REPLACE PROCEDURE AIRLINE_DWH.ANALYTICS.sp_process_staging_to_analytics()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  rows_inserted_fact INT := 0;
  error_message VARCHAR;
BEGIN
    BEGIN TRANSACTION;

    MERGE INTO AIRLINE_DWH.ANALYTICS.DIM_PASSENGER d
    USING (SELECT DISTINCT PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY FROM AIRLINE_DWH.STAGING.STG_FLIGHTS) s
    ON d.passenger_id = s.PASSENGER_ID
    WHEN NOT MATCHED THEN INSERT (passenger_id, first_name, last_name, gender, age, nationality)
    VALUES (s.PASSENGER_ID, s.FIRST_NAME, s.LAST_NAME, s.GENDER, s.AGE, s.NATIONALITY);

    MERGE INTO AIRLINE_DWH.ANALYTICS.DIM_PILOT d
    USING (SELECT DISTINCT PILOT_NAME FROM AIRLINE_DWH.STAGING.STG_FLIGHTS) s
    ON d.pilot_name = s.PILOT_NAME
    WHEN NOT MATCHED THEN INSERT (pilot_name) VALUES (s.PILOT_NAME);

    MERGE INTO AIRLINE_DWH.ANALYTICS.DIM_AIRPORT d
    USING (
        SELECT DISTINCT AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, CONTINENTS FROM AIRLINE_DWH.STAGING.STG_FLIGHTS
        UNION
        SELECT DISTINCT ARRIVAL_AIRPORT, NULL, NULL, NULL FROM AIRLINE_DWH.STAGING.STG_FLIGHTS WHERE ARRIVAL_AIRPORT IS NOT NULL
    ) s
    ON d.airport_name = s.AIRPORT_NAME
    WHEN NOT MATCHED THEN INSERT (airport_name, airport_code, country_name, continent) VALUES (s.AIRPORT_NAME, s.AIRPORT_COUNTRY_CODE, s.COUNTRY_NAME, s.CONTINENTS);

    INSERT INTO AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS (
        passenger_key, departure_airport_key, arrival_airport_key, pilot_key,
        departure_date, flight_status, ticket_type
    )
    SELECT
        p.passenger_key, da.airport_key, aa.airport_key, pi.pilot_key,
        s.DEPARTURE_DATE, s.FLIGHT_STATUS, s.TICKET_TYPE
    FROM AIRLINE_DWH.STAGING.STG_FLIGHTS s
    LEFT JOIN AIRLINE_DWH.ANALYTICS.DIM_PASSENGER p ON s.PASSENGER_ID = p.passenger_id
    LEFT JOIN AIRLINE_DWH.ANALYTICS.DIM_AIRPORT da ON s.AIRPORT_NAME = da.airport_name
    LEFT JOIN AIRLINE_DWH.ANALYTICS.DIM_AIRPORT aa ON s.ARRIVAL_AIRPORT = aa.airport_name
    LEFT JOIN AIRLINE_DWH.ANALYTICS.DIM_PILOT pi ON s.PILOT_NAME = pi.pilot_name;

    rows_inserted_fact := SQLROWCOUNT;

    INSERT INTO AIRLINE_DWH.AUDIT.ETL_LOG (procedure_name, table_name, rows_inserted)
    VALUES ('sp_process_staging_to_analytics', 'FACT_FLIGHTS', :rows_inserted_fact);

    TRUNCATE TABLE AIRLINE_DWH.STAGING.STG_FLIGHTS;

    COMMIT;
    RETURN 'Fact table loaded. Rows inserted: ' || rows_inserted_fact;

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        error_message := 'Error: ' || SQLERRM || ' (SQLSTATE: ' || SQLSTATE || ')';
        RETURN :error_message;
END;
$$;