USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE AIRLINE_DWH;

UPDATE AIRLINE_DWH.ANALYTICS.DIM_PASSENGER SET NATIONALITY = 'Kryptonian' WHERE PASSENGER_ID = 'AB-12345';

SELECT * FROM AIRLINE_DWH.ANALYTICS.DIM_PASSENGER AT(OFFSET => -60*5) WHERE PASSENGER_ID = 'AB-12345';

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGING.TEMP_FOR_DELETE (id INT);

DROP TABLE AIRLINE_DWH.STAGING.TEMP_FOR_DELETE;

UNDROP TABLE AIRLINE_DWH.STAGING.TEMP_FOR_DELETE;

CREATE OR REPLACE TABLE AIRLINE_DWH.ANALYTICS.DIM_PASSENGER_BACKUP
CLONE AIRLINE_DWH.ANALYTICS.DIM_PASSENGER AT(OFFSET => -60*60);

CREATE OR REPLACE ROLE ANALYST_EU;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_EU;
GRANT USAGE ON DATABASE AIRLINE_DWH TO ROLE ANALYST_EU;
GRANT USAGE ON SCHEMA AIRLINE_DWH.ANALYTICS TO ROLE ANALYST_EU;
GRANT ROLE ANALYST_EU TO USER AIRFLOW_USER;

CREATE OR REPLACE TABLE AIRLINE_DWH.AUDIT.RLS_CONTINENT_ACCESS (
  ROLE_NAME VARCHAR,
  ALLOWED_CONTINENT VARCHAR
);

INSERT INTO AIRLINE_DWH.AUDIT.RLS_CONTINENT_ACCESS VALUES ('ANALYST_EU', 'Europe');

CREATE OR REPLACE ROW ACCESS POLICY AIRLINE_DWH.ANALYTICS.continent_policy
AS (continent_val VARCHAR) RETURNS BOOLEAN ->
  CURRENT_ROLE() = 'ACCOUNTADMIN'
  OR EXISTS (
    SELECT 1 FROM AIRLINE_DWH.AUDIT.RLS_CONTINENT_ACCESS
    WHERE ROLE_NAME = CURRENT_ROLE()
      AND ALLOWED_CONTINENT = continent_val
  );

CREATE OR REPLACE SECURE VIEW AIRLINE_DWH.ANALYTICS.V_SECURE_FLIGHTS AS
SELECT
    f.*,
    da.continent AS departure_continent
FROM
    AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS f
JOIN
    AIRLINE_DWH.ANALYTICS.DIM_AIRPORT da ON f.departure_airport_key = da.airport_key;

ALTER VIEW AIRLINE_DWH.ANALYTICS.V_SECURE_FLIGHTS
ADD ROW ACCESS POLICY AIRLINE_DWH.ANALYTICS.continent_policy ON (departure_continent);

GRANT SELECT ON VIEW AIRLINE_DWH.ANALYTICS.V_SECURE_FLIGHTS TO ROLE ANALYST_EU;